image: node:8.12

pipelines:
  default:
    - step:
        script:
          - npm ci
          - apt-get update && apt-get install -y python-dev
          - curl -O https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install awscli
          - aws cloudformation deploy --stack-name s3BucketCreation --template-file  ./template.yml --parameter-overrides BucketName=bjohns.first.bucket 
