AWSTemplateFormatVersion: 2010-09-09
Description: Creating S3 Bucket
Parameters:
  BucketName:
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: 'PublicRead'
      BucketName: !Ref BucketName
Outputs:
  BucketName:
    Value: !Ref Bucket
    Description: Name of the sample Amazon S3 bucket
